-- ============================================
-- Auto-generated seed for: Day 5: Photovoltaics
-- Source API ID: 1419
-- Generated: 2026-02-26T11:43:29.639Z
-- ============================================

-- ============================================
-- Day 5: Photovoltaics - Part 2: Photovoltaics
-- ============================================

INSERT INTO public.tests (id, title, description, difficulty_level, is_published)
VALUES (
    '801e7fef-f1cd-4fbd-96c8-919f7c1c776d',
    'Day 5: Photovoltaics - Part 2: Photovoltaics',
    'Cambridge IELTS - Photovoltaics',
    'medium',
    true
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.reading_passages (id, test_id, passage_number, title, content, word_count, time_limit)
VALUES (
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    '801e7fef-f1cd-4fbd-96c8-919f7c1c776d',
    1,
    'Photovoltaics',
    'Residential use of photovoltaics – by day excess power is sent to the grid, and by night power is supplied to the home.

A 
In the past, urban home owners have not always had much choice in the way electricity is supplied to their homes. Now, however, there is a choice, and a rapidly increasing number of households worldwide are choosing the solar energy option. Solar energy, the conversion of sunlight into energy, is made possible through the use of ‘photovoltaics’, which are simple appliances that fit onto the roof of a house.

B 
The photovoltaic-powered home remains connected to the power lines, but no storage is required on-site, only a box of electronics (the inverter) to interface between the photovoltaics and the grid network. Figure 1 illustrates the system. During the day, when the home may not be using much electricity, excess power from the solar array is fed back to the grid, to factories offices that need daytime power. At night, power flows the opposite way. The grid network effectively provides storage. If the demand for electricity is well matched to when the sun shines, solar energy is especially valuable. This occurs in places like California in the US and Japan, where air-conditioning loads for offices and factories are large but heating loads for the home are small.

C 
The first systematic exploration of the use of photovoltaics on homes began in the US during the 1970s, a well-conceived program started with the siting of a number of ‘residential experiment stations’ at selected locations around the country, representing different climatic zones. These stations contained a number of ‘dummy’ houses, each with a different solar-energy system design. Homes within the communities close to these stations were monitored to see how well their energy use matched the energy generated by the stations’ dummy roofs. A change in US government priorities in the early 1980s halted this program.

D 
With the US effort dropping away, the Japanese Sunshine Project came to the fore. A large residential test station was installed on Rokko Island beginning in 1986. This installation consists of 18 ‘dummy’ house, each equipped with its own 2-5 kilowatt photovoltaic system (about 20-50 square metres for each system). For the other systems, electronics simulate these household loads. This test station has allowed the technical issues involved in using photovoltaics within the electricity network to be explored in a systematic way, under well-controlled test conditions. With no insurmountable problems identified, the Japanese have used the experience gained from this station to begin their own massive residential photovoltaics campaign.

E 
Meanwhile, Germany began a very important ‘1000 roof program’ in 1990, aimed at installing photovoltaics on the roofs of 1000 private homes. Large federal and regional government subsidies were involved, accounting in most cases for 70 per cent of the total system costs. The program proved immensely popular, forcing its extension to over 2000 homes scattered across Germany. The success of this program stimulated other European countries to launch similar programs.

F 
Japan’s ‘one million roof program’ was prompted by the experience gained in the Rokko Island test site and success of the German 1000 roof program. The initially quoted aims of the Japanese New Energy Development Organisation were to have 70,000 homes equipped with photovoltaics by the year 2000, on the way to one million by 2020. The program made a modest start in 1994, when 539 systems were installed with a government subsidy of 50 per cent. Under this program, entire new suburban developments are using photovoltaics.

G 
The Japanese initiative in embracing residential photovoltaics on a large scale prompted responses in both Europe and the US. The European Commission has called for one million solar residential systems before the year 2010, with 500,000 in Europe and 500,000 in the developing world, to be subsidised by the Commission. In 1997, a similar one million roof target was announced in the US. Since then, several other countries including Germany, Italy, the Netherlands and Australia, have announced their own targets for residential photovoltaics.

H 
This is good news, not only for the photovoltaic industry, but for everyone concerned with the environment. The use of fossil fuels to generate electricity is not only costly in financial terms, but also in terms of environmental damage. Gases produced by the burning of fossil fuels in the production of electricity are a major contributor to the greenhouse effect. To deal with this problem, many governments are now proposing stringent targets on the amount of greenhouse gas emissions permitted. These targets mean that all sources of greenhouse gas emissions, including residential electricity use, will receive closer attention in the future.

I 
It is likely that, in the future, governments will develop building codes that attempt to constrain the energy demands of new housing. For example, the use of photovoltaics or the equivalent may be stipulated to lessen demands on the grid network and hence reduce fossil fuel emissions. Approvals for building renovations may also be conditional upon talking such energy-saving measures. If this were to happen, everyone would benefit. Although there is an initial cost in attaching the system to the rooftop, the householder’s outlay is soon compensated with the savings on energy bills. In addition, everyone living on the planet stands to gain from the more benign environmental impact.',
    883,
    1200
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    '9b0cbc87-123b-4437-8421-8d12841b4f16',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    14,
    'matching_info',
    'Examples of countries where electricity use is greater during the day than at night',
    '["","","","","","","","",""]'::jsonb,
    'B',
    NULL,
    1,
    '{"instruction":"<p>The text has nine paragraphs, A-I. Which paragraph contains the following information?</p><p><strong>NB</strong> <em>You may choose any paragraph more than once.</em></p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    '9c6f8373-ddd0-4b0b-bc9d-78fcd68bbc74',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    15,
    'matching_info',
    'A detailed description of an experiment that led to photovoltaics being promoted throughout the country',
    '["","","","","","","","",""]'::jsonb,
    'D',
    NULL,
    1,
    '{"instruction":"<p>The text has nine paragraphs, A-I. Which paragraph contains the following information?</p><p><strong>NB</strong> <em>You may choose any paragraph more than once.</em></p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    'a7d6c412-05a0-4a58-b695-1bb1648a61dc',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    16,
    'matching_info',
    'The negative effects of using conventional means of generating electricity',
    '["","","","","","","","",""]'::jsonb,
    'H',
    NULL,
    1,
    '{"instruction":"<p>The text has nine paragraphs, A-I. Which paragraph contains the following information?</p><p><strong>NB</strong> <em>You may choose any paragraph more than once.</em></p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    '9264ac50-fe10-4243-af63-2024fb42a321',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    17,
    'matching_info',
    'An explanation of the photovoltaic system',
    '["","","","","","","","",""]'::jsonb,
    'B',
    NULL,
    1,
    '{"instruction":"<p>The text has nine paragraphs, A-I. Which paragraph contains the following information?</p><p><strong>NB</strong> <em>You may choose any paragraph more than once.</em></p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    '0c7c97a7-a422-44a5-9ea3-d993cbc71860',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    18,
    'matching_info',
    'The long-term benefits of using photovoltaics',
    '["","","","","","","","",""]'::jsonb,
    'I',
    NULL,
    1,
    '{"instruction":"<p>The text has nine paragraphs, A-I. Which paragraph contains the following information?</p><p><strong>NB</strong> <em>You may choose any paragraph more than once.</em></p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    'bf378e04-97b7-4815-ab91-01b88e9b1408',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    19,
    'matching_info',
    'A reference to wealthy countries being prepared to help less wealthy countries have access to photovoltaics',
    '["","","","","","","","",""]'::jsonb,
    'G',
    NULL,
    1,
    '{"instruction":"<p>The text has nine paragraphs, A-I. Which paragraph contains the following information?</p><p><strong>NB</strong> <em>You may choose any paragraph more than once.</em></p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    'd71258b2-bda6-4078-a134-3d0418980516',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    20,
    'tfng',
    'Photovoltaics are used to store electricity.',
    NULL,
    'FALSE',
    NULL,
    1,
    '{"instruction":"<p>Choose&nbsp;<strong>TRUE</strong>&nbsp;if the statement agrees with the information given in the text, choose&nbsp;<strong>FAL<span class=\"ql-cursor\">﻿</span>SE</strong>&nbsp;if the statement contradicts the information, or choose&nbsp;<strong>NOT GIVEN</strong>&nbsp;if there is no information on this.</p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    'bbb7016d-4809-4c1c-b5e1-0a57d041e85c',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    21,
    'tfng',
    'Since the 1970s, the US government has provided continuous support for the use of photovoltaics on homes.',
    NULL,
    'FALSE',
    NULL,
    1,
    '{"instruction":"<p>Choose&nbsp;<strong>TRUE</strong>&nbsp;if the statement agrees with the information given in the text, choose&nbsp;<strong>FAL<span class=\"ql-cursor\">﻿</span>SE</strong>&nbsp;if the statement contradicts the information, or choose&nbsp;<strong>NOT GIVEN</strong>&nbsp;if there is no information on this.</p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    'f479f6b7-349f-4083-a50f-78ce828db6b9',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    22,
    'tfng',
    'The solar-powered houses on Rokko Island are uninhabited.',
    NULL,
    'TRUE',
    NULL,
    1,
    '{"instruction":"<p>Choose&nbsp;<strong>TRUE</strong>&nbsp;if the statement agrees with the information given in the text, choose&nbsp;<strong>FAL<span class=\"ql-cursor\">﻿</span>SE</strong>&nbsp;if the statement contradicts the information, or choose&nbsp;<strong>NOT GIVEN</strong>&nbsp;if there is no information on this.</p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    'c3ff95b6-3aa7-4efa-b7bc-916990ba3fb4',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    23,
    'tfng',
    'In 1994, the Japanese government was providing half the money required for installing photovoltaics on homes.',
    NULL,
    'TRUE',
    NULL,
    1,
    '{"instruction":"<p>Choose&nbsp;<strong>TRUE</strong>&nbsp;if the statement agrees with the information given in the text, choose&nbsp;<strong>FAL<span class=\"ql-cursor\">﻿</span>SE</strong>&nbsp;if the statement contradicts the information, or choose&nbsp;<strong>NOT GIVEN</strong>&nbsp;if there is no information on this.</p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    '89c1ca87-81da-4eaf-be88-05e34e91586f',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    24,
    'tfng',
    'Germany, Italy, the Netherlands and Australia all have strict goals with regard to greenhouse gas emissions.',
    NULL,
    'NOT GIVEN',
    NULL,
    1,
    '{"instruction":"<p>Choose&nbsp;<strong>TRUE</strong>&nbsp;if the statement agrees with the information given in the text, choose&nbsp;<strong>FAL<span class=\"ql-cursor\">﻿</span>SE</strong>&nbsp;if the statement contradicts the information, or choose&nbsp;<strong>NOT GIVEN</strong>&nbsp;if there is no information on this.</p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    '0c10d8f3-ad8d-4090-88cd-58fc1bd54dbf',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    25,
    'tfng',
    'Residential electricity use is the major source of greenhouse gas emissions.',
    NULL,
    'NOT GIVEN',
    NULL,
    1,
    '{"instruction":"<p>Choose&nbsp;<strong>TRUE</strong>&nbsp;if the statement agrees with the information given in the text, choose&nbsp;<strong>FAL<span class=\"ql-cursor\">﻿</span>SE</strong>&nbsp;if the statement contradicts the information, or choose&nbsp;<strong>NOT GIVEN</strong>&nbsp;if there is no information on this.</p>"}'::jsonb
);

INSERT INTO public.questions (id, module_type, section_id, question_number, question_type, question_text, options, correct_answer, explanation, points, metadata)
VALUES (
    '4f6a89b1-da69-42a0-8b3c-71ebc5334419',
    'reading',
    '65f240bb-0d09-4388-b855-eb1cde0a02d2',
    26,
    'tfng',
    'Energy-saving measures must now be included in the design of all new homes and improvements to buildings.',
    NULL,
    'FALSE',
    NULL,
    1,
    '{"instruction":"<p>Choose&nbsp;<strong>TRUE</strong>&nbsp;if the statement agrees with the information given in the text, choose&nbsp;<strong>FAL<span class=\"ql-cursor\">﻿</span>SE</strong>&nbsp;if the statement contradicts the information, or choose&nbsp;<strong>NOT GIVEN</strong>&nbsp;if there is no information on this.</p>"}'::jsonb
);

